export const teachers = [
  "Saiid Bachir",
  "Antonio Fahed",
  "Laureine Atallah-Baradhi",
  "Joe Awad",
  "Gisèle Badaoui-Chalhoub",
  "Samir Boulos",
  "Charbel Chemali",
  "Maria Corm-Stephan",
  "Tatiana Dagher",
  "Toni Francis",
  "Rima Ghannam",
  "Salim Geara",
  "Charbel Helou",
  "Zalfa Khalil-El-Khazen",
  "Naamen Karam",
  "Antoine Medawar",
  "Georgio Mouawad",
  "Myriam Mansour",
  "Rock Mhanna",
  "Layal Nakhoul-Challita",
  "Serge Nasrallah",
  "Ziad Otayek",
  "Charbel Berkachi",
  "Georges Saber",
  "Michel Tabet",
  "Micheline Wehbe",
  "Laure Yazbeck",
  "Rita Hokayem",
  "Aline Geagea",
  "Pierre Chammas",
  "Rima Hanna",
  "George Bouchaaya",
  "joseph el hage"


];